site_name: Julius Richter
markdown_extensions:
  - def_list
  - attr_list
  - toc:
      permalink: 2
nav:
  - 'Julius Richter: Fiktive Buchrezension': index.md
  - Zum Spiel: ./game/game.html
  - Zu den einzelnen Stationen: stationen.md
  - Bestandsbeschreibung: bestandsbeschreibung.md
  - Weitere Links: links.md
theme:
  name: material
  logo: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Zum Darkmode wechseln
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Zum Lightmode wechseln
